spring.application.name=webapp

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

jwt.signerKey=${JWT_SIGNER_KEY}

server.servlet.context-path=/api/v1

# Hiển thị các câu lệnh SQL (INSERT, UPDATE...) lên màn hình console để dễ tìm lỗi
spring.jpa.show-sql=true

# Định dạng câu lệnh SQL in ra cho đẹp và dễ đọc
spring.jpa.properties.hibernate.format_sql=true

# BÁU VẬT CỦA JPA: Tự động quản lý bảng
spring.jpa.hibernate.ddl-auto=update 





